channels:
- anaconda
- conda-forge
dependencies:
- python=3.8.13
- ncurses
- pip
- pip:
  - hyperopt==0.2.7
  - joblib==1.2.0
  - langchain==0.0.327
  - matplotlib==3.2.1
  - nlpaug==1.1.11
  - nltk==3.8.1
  - numpy==1.21.6
  - openai==0.27.8
  - optuna==3.3.0
  - pandas==1.2.0
  - petname==2.6
  - pyspark==3.3.1
  - pytest==7.4.2
  - python-dotenv==1.0.0
  - scikit_learn==1.3.1
  - sentence_transformers==2.2.2
  - tenacity==8.2.2
  - test_utils==0.1.0
  - textattack==0.3.9
  - torch==1.12.0
  - tqdm==4.65.0
  - transformers==4.30.0
  - xgboost==1.3.3
  - azure-ai-ml==1.11.1
  - azureml-core==1.53.0
  - azureml==0.2.7
  - azureml-inference-server-http==1.0.0
  - azureml-dataset-runtime==1.54.0
name: embeddings_main_A
